import Foundation

public enum MarkdownHTMLEntity {
    public static func character(for source: String) -> String? {
        guard source.hasPrefix("&"), source.hasSuffix(";") else { return nil }
        let body = source.dropFirst().dropLast()
        guard !body.isEmpty else { return nil }

        if body.hasPrefix("#x") || body.hasPrefix("#X") {
            return scalarString(from: body.dropFirst(2), radix: 16)
        }

        if body.hasPrefix("#") {
            return scalarString(from: body.dropFirst(), radix: 10)
        }

        return namedEntities[String(body)]
    }

    private static func scalarString<S: StringProtocol>(from value: S, radix: Int) -> String? {
        guard !value.isEmpty, let scalarValue = UInt32(value, radix: radix) else { return nil }
        guard let scalar = UnicodeScalar(scalarValue) else { return nil }
        return String(Character(scalar))
    }

    private static let namedEntities: [String: String] = [
        "AElig": "Æ",
        "Aacute": "Á",
        "Acirc": "Â",
        "Agrave": "À",
        "Aring": "Å",
        "Atilde": "Ã",
        "Auml": "Ä",
        "Ccedil": "Ç",
        "ETH": "Ð",
        "Eacute": "É",
        "Ecirc": "Ê",
        "Egrave": "È",
        "Euml": "Ë",
        "Iacute": "Í",
        "Icirc": "Î",
        "Igrave": "Ì",
        "Iuml": "Ï",
        "Ntilde": "Ñ",
        "Oacute": "Ó",
        "Ocirc": "Ô",
        "Ograve": "Ò",
        "Oslash": "Ø",
        "Otilde": "Õ",
        "Ouml": "Ö",
        "THORN": "Þ",
        "Uacute": "Ú",
        "Ucirc": "Û",
        "Ugrave": "Ù",
        "Uuml": "Ü",
        "Yacute": "Ý",
        "aacute": "á",
        "acirc": "â",
        "acute": "'",
        "aelig": "æ",
        "agrave": "à",
        "amp": "&",
        "apos": "'",
        "aring": "å",
        "asymp": "≈",
        "atilde": "ã",
        "auml": "ä",
        "alpha": "α",
        "bdquo": "„",
        "beta": "β",
        "brvbar": "¦",
        "bull": "•",
        "ccedil": "ç",
        "cedil": "¸",
        "cent": "¢",
        "copy": "©",
        "curren": "¤",
        "dagger": "†",
        "deg": "°",
        "divide": "÷",
        "delta": "δ",
        "eacute": "é",
        "ecirc": "ê",
        "egrave": "è",
        "empty": "∅",
        "emsp": "\u{2003}",
        "ensp": "\u{2002}",
        "eth": "ð",
        "euml": "ë",
        "euro": "€",
        "exist": "∃",
        "fnof": "ƒ",
        "forall": "∀",
        "frac12": "1/2",
        "frac14": "1/4",
        "frac34": "3/4",
        "ge": "≥",
        "geq": "≥",
        "gamma": "γ",
        "gt": ">",
        "hellip": "…",
        "infin": "∞",
        "iacute": "í",
        "icirc": "î",
        "iexcl": "¡",
        "igrave": "ì",
        "isin": "∈",
        "iquest": "¿",
        "iuml": "ï",
        "laquo": "«",
        "ldquo": "“",
        "le": "≤",
        "leq": "≤",
        "lsaquo": "‹",
        "lsquo": "‘",
        "lt": "<",
        "macr": "¯",
        "mdash": "—",
        "micro": "µ",
        "middot": "·",
        "minus": "−",
        "nbsp": "\u{00A0}",
        "ndash": "–",
        "ne": "≠",
        "not": "¬",
        "notin": "∉",
        "ntilde": "ñ",
        "oacute": "ó",
        "ocirc": "ô",
        "ograve": "ò",
        "ordf": "ª",
        "ordm": "º",
        "oslash": "ø",
        "otilde": "õ",
        "ouml": "ö",
        "para": "¶",
        "permil": "‰",
        "pi": "π",
        "plusmn": "±",
        "pound": "£",
        "prime": "′",
        "Prime": "″",
        "prod": "∏",
        "prop": "∝",
        "quot": "\"",
        "raquo": "»",
        "radic": "√",
        "rdquo": "”",
        "reg": "®",
        "rsaquo": "›",
        "rsquo": "’",
        "sect": "§",
        "shy": "\u{00AD}",
        "sigma": "σ",
        "sup1": "¹",
        "sup2": "²",
        "sup3": "³",
        "sum": "∑",
        "szlig": "ß",
        "thinsp": "\u{2009}",
        "thorn": "þ",
        "times": "×",
        "trade": "™",
        "uacute": "ú",
        "ucirc": "û",
        "ugrave": "ù",
        "uuml": "ü",
        "yacute": "ý",
        "yen": "¥",
        "yuml": "ÿ",
        "zwj": "\u{200D}",
        "zwnj": "\u{200C}"
    ]
}
